import { StateGraph, StateSchema, START, END } from '@langchain/langgraph'
import { mistralAIModel, cohereModel, geminiModel } from "./model.ai.js"
import z from 'zod'
import { createAgent, providerStrategy } from 'langchain'
import { HumanMessage } from '@langchain/core/messages'

const GraphState = new StateSchema({
    problem: z.string().default(""),
    solution_1: z.string().default(""),
    solution_2: z.string().default(""),
    judge: z.object({
        solution_core_1: z.number().default(0),
        solutin_core_2: z.number().default(0),
        solution_1_reasoning: z.string().default(""),
        solution_2_reasoning: z.string().default(""),
    })

})

const solutionNode = async (state: typeof GraphState.State) => {
    const [mistralResponse, cohereResponse] = await Promise.all([
        mistralAIModel.invoke(state.problem),
        cohereModel.invoke(state.problem)
    ])

    return {
        solution_1: mistralResponse.text,
        solution_2: cohereResponse.text,
    }


}

const judgeNode = async (state: typeof GraphState.State) => {
    const { problem, solution_1, solution_2 } = state


    const judge = createAgent({
        model: geminiModel,
        responseFormat: providerStrategy(z.object({
            solution_1_score: z.number().min(0).max(10),
            solution_2_score: z.number().min(0).max(10),
            solution_1_reasoning: z.string(),
            solution_2_reasoning: z.string(),

        })),
        systemPrompt: `You are a judge tasked with evaluating two solutions generated by different AI models.
        Please provide a score out of 10 for each solution, along with your reasoning for the scores.`
    })
    const judgeResponse = await judge.invoke({
        messages: [
            new HumanMessage(`
                Problem: ${problem}
                solution 1: ${solution_1}
                solution 2: ${solution_2}
                Please evaluate the solutions and provide score and reasoning.`)
        ]
    })

    const {
        solution_1_score,
        solution_2_score,
        solution_1_reasoning,
        solution_2_reasoning
    } = judgeResponse.structuredResponse as {
        solution_1_score: number;
        solution_2_score: number;
        solution_1_reasoning: string;
        solution_2_reasoning: string;
    }

    return {
        judge: {
            solution_core_1: solution_1_score,
            solutin_core_2: solution_2_score,
            solution_1_reasoning,
            solution_2_reasoning,
        }
    }
}

const graph = new StateGraph({ state: GraphState })
    .addNode("solution", solutionNode)
    .addNode("judge_node", judgeNode)
    .addEdge(START, "solution")
    .addEdge("solution", "judge_node")
    .addEdge("judge_node", END)
    .compile()

export default async function (problem: string) {

    const result = await graph.invoke({
        problem: problem
    })

    return result
}